language: haxe
sudo: required
haxe:
  - "3.4.7"
  - stable # the latest stable release defined in https://haxe.org/download/list/
services:
  - mysql
addons:
  hosts:
    - cagette
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y curl imagemagick gettext apache2 libapache2-mod-neko libmysqlclient-dev
  - sudo a2enmod neko
  - sudo a2enmod rewrite
  # For the following apache2 related operations, see https://docs.travis-ci.com/user/languages/php#Apache-%2B-PHP
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
  - mysql -e 'CREATE DATABASE cagette;'
  - mysql -e 'CREATE DATABASE tests;'
  - cp config.xml.dist config.xml
  - sed -e 's?database=.*?database="mysql://root:@localhost/cagette"?g' --in-place config.xml
  - sed -e 's?debug=.*?debug="1"?g' --in-place config.xml
  - sed -e 's?langs=.*?langs="fr;de;en"?g' --in-place config.xml
  - sed -e 's?langnames=.*?langnames="Fran√ßais;Deutsch;English"?g' --in-place config.xml
install:
  - yes | haxelib install alterconso.hxml
  - yes | haxelib install alterconsoJs.hxml
before_script:
  - sudo sh -c "cd /usr/bin;haxelib run templo"
  - npm install
script:
  - if [ ! -e www/index.n ]; then echo "File www/index.n does not exist yet, as expected"; else echo "Unexpected file www/index.n exists, but it should not exist yet" && exit 1; fi
  - haxe alterconso.hxml
  - if [ -e www/index.n ]; then echo "File www/index.n now exists, as expected"; else echo "Unexpected error, file www/index.n does not exist yet, but it should" && exit 1; fi
  - haxe alterconsoJs.hxml
  - npm run libs:dev
  - npm run build:js
  - first_access_index_page_output=$(wget http://cagette -O-)
  - echo $first_access_index_page_output
  - if [ "$(echo \"$first_access_index_page_output\" | grep 'INSERT INTO Error' | wc -l)" = "0" ]; then echo "[First page access] First page access does not show an error, but we expect it to show an error the first time it is accessed" && exit 1; else echo "[First page access] First page access shows an error, as expected"; fi
  - second_access_index_page_output=$(wget http://cagette -O-)
  - echo $second_access_index_page_output
  - if [ "$(echo \"$second_access_index_page_output\" | grep 'CONTACTEZ-NOUS' | wc -l)" != "1" ]; then echo "[Second page access] Second page access does not show a single 'CONTACTEZ-NOUS' text, but it should" && exit 1; else echo "[Second page access] Second page access shows a single 'CONTACTEZ-NOUS' text, as expected"; fi
  - haxe tests.hxml
  - cd www && neko tests.n mysql://root:@localhost/tests